knp_paginator:
    # number of links shown in the pagination menu
    # (e.g: for 10 pages and a page_range of 3, on the 5th page you'll see links to page 4, 5, 6)
    page_range: 3
    # remove the page query parameter from the first page link
    remove_first_page_param: false
    default_options:
        # page query parameter name
        page_name: page
        # sort field query parameter name
        sort_field_name: sort
        # sort direction query parameter name
        sort_direction_name: direction
        # ensure distinct results, useful when ORM queries are using GROUP BY statements
        distinct: true
        # filter field query parameter name
        filter_field_name: filterField
        # filter value query parameter name
        filter_value_name: filterValue
        # ignore, fix, or throwException when the page is out of range
        page_out_of_range: ignore
        # default number of items per page
        default_limit: 9

    # Default templates for rendering pagination
    template:
        # pagination controls template
        # pagination: '@KnpPaginator/Pagination/sliding.html.twig'
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig'
        # sort link template
        # sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'
        sortable: '@KnpPaginator/Pagination/bootstrap_v5_bi_sortable_link.html.twig'
        # filters template
        # filtration: '@KnpPaginator/Pagination/filtration.html.twig'
        filtration: '@KnpPaginator/Pagination/bootstrap_v5_filtration.html.twig'

        # suggestions chatgtp
        # pagination: 'knp_paginator/pagination.html.twig'
